# Generated by Django 4.1 on 2022-10-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
