# Generated by Django 4.1 on 2022-10-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0010_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/2022/10/default.png', upload_to='profile/%Y/%m'),
        ),
    ]
